# -*- coding: utf-8 -*-
"""Actividad4_de_problematización_Mario_Hernández.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUog_S67sZk4M_0m0qRdoaBlqQVKV6Ra

# **1) Programa utilizando listas**
"""

# Lista para almacenar los clientes
clientes = []

# Ciclo while para ejecutar el programa y las opciones del menú
while True:
    print("\n Programa Gestión de Clientes: ")
    print("1. Añadir cliente")
    print("2. Eliminar cliente")
    print("3. Modificar cliente")
    print("4. Listar/Ordenar clientes por Nombre")
    print("5. Listar/Ordenar clientes por Edad")
    print("6. Listar/Ordenar clientes por Valor de la compra $")
    print("7. Consultar cliente por ID")
    print("8. Salir")

    # Pedimos la opcion del menú y la casteamos en int y así también con las opciones de añadir cliente
    opcion = int(input("Por favor selecciona una opción: "))

    if opcion == 1:
        # Añadir cliente
        id = int(input("Por favor, ingrese el ID del cliente: "))
        nombre = input("Por favor, ingrese el nombre del cliente: ")
        correo = input("Por favor, ingrese el correo del cliente: ")
        telefono = input("Por favor, ingrese el teléfono del cliente: ")
        edad = int(input("Por favor, ingrese la edad del cliente: "))
        v_compra = float(input("Por favor, ingrese el valor de la compra del cliente: $"))
        ciudad = input("Por favor, ingrese la ciudad del cliente: ")

        # Se crea un diccionario con los datos del cliente ingresados
        cliente = {'ID': id, 'Nombre': nombre, 'Correo': correo, 'Teléfono': telefono,
            'Edad': edad, 'Valor de la Compra': v_compra, 'Ciudad': ciudad}

        # Se agregan a la lista los datos
        clientes.append(cliente)
        print("El cliente se ha agregado al sistema")

         # Realizamos un ciclo para recorrer todos los elementos de clientes y poder mostrarlos
        print("\nLista de todos los clientes:")
        for cliente in clientes:
            print(cliente)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 2:
        # Eliminar cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a eliminar: "))

        # Se crea una nueva lista de clientes que no contenga al cliente con el ID especificado
        # Para eso realizamos un ciclo para recorrer todos los elementos de clientes
        # Y la condición verifica si el valor de 'ID' en el diccionario es diferente del valor de id que se quiere eliminar
        # los clientes que cumplen con esta condición se dejan en la nueva lista.

        clientes = [cliente for cliente in clientes if cliente['ID'] != id]
        print("El cliente ha sido eliminado del sistema")
        input("Por favor presiona ENTER para continuar")

    elif opcion == 3:
        # Modificar datos del cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a modificar: "))

        # Realizamos un ciclo para recorrer todos los elementos de clientes y poder modificarlos
        for cliente in clientes:

            # Verificamos si el ID del cliente es igual al ID que se quiere modificar
            if cliente['ID'] == id:
                nombre = input("Por favor, ingrese el nuevo nombre del cliente: ")
                correo = input("Por favor, ingrese el nuevo correo del cliente: ")
                telefono = input("Por favor, ingrese el nuevo teléfono del cliente: ")
                edad = input("Por favor, ingrese la nueva edad del cliente: ")
                v_compra = input("Por favor, ingrese el nuevo valor de la compra del cliente: $")
                ciudad = input("Por favor, ingrese la nueva ciudad del cliente: ")

                # Se verifica si se ha modificado la información en cada campo con un condicional
                # de True o Flase y en caso de ser True se reemplaza el dato en el campo respectivo
                # y se añade a la lista clientes.

                if nombre:
                    cliente['Nombre'] = nombre
                if correo:
                    cliente['Correo'] = correo
                if telefono:
                    cliente['Teléfono'] = telefono
                if edad:
                    cliente['Edad'] = int(edad)
                if v_compra:
                    cliente['Valor de la Compra'] = float(v_compra)
                if ciudad:
                    cliente['Ciudad'] = ciudad

                print("El cliente se ha modificado en el sistema.")
                input("Por favor presiona ENTER para continuar")
                break

    elif opcion == 4:

        # Listar/Ordenar clientes por nombre
        # Ordenamos por Nombre usando la función sorted
        # En este caso usamos lambda x: que es una función anónima
        # que toma un cliente (x) y devuelve su nombre, con el fin de
        # poder ordenar los clientes alfabéticamente por su nombre.

        clientes_ordenados = sorted(clientes, key=lambda x: x['Nombre'])

        # Aqui se imprimime los clientes ya ordenados por nombre
        for cliente in clientes_ordenados:
            print(cliente)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 5:
        # Listar/Ordenar clientes por edad
        # Aqui se ordenan los clientes usando la función sorted con el
        # mismo principio utilizado en la anterior función
        clientes_ordenados = sorted(clientes, key=lambda x: x['Edad'])

        # Aqui se imprimime los clientes ya ordenados por la edad
        for cliente in clientes_ordenados:
            print(cliente)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 6:
        # Listar/Ordenar clientes por valor de la compra
        # Aqui se ordenan los clientes usando la función sorted con el
        # mismo principio utilizado en la anterior función
        clientes_ordenados = sorted(clientes, key=lambda x: x['Valor de la Compra'])

        # Aqui se imprimime los clientes ya ordenados por el valor de la compra
        for cliente in clientes_ordenados:
            print(cliente)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 7:
        # Consultar cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a consultar: "))

        # Recorre todos los elementos de clientes para buscar el ID y mostrar la información
        # con ayuda de un condicional
        for cliente in clientes:
            if cliente['ID'] == id:
                print(cliente)
                break
        input("Por favor presiona ENTER para continuar")

    elif opcion == 8:
        print("--> Saliendo del programa--->")

        # Usamos break para terminar el ciclo While del menú
        break

    # En el caso de elegir una opción distinta a las mostradas se indica que esta opción
    # no es válida y se le pide al usuario que intente de nuevo
    else:
        print("Opción no válida, por favor intente de nuevo.")
        input("Por favor presiona ENTER para continuar")

"""# **2) Programa utilizando una base de datos con DataFrame**"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

excel_path = "/content/drive/MyDrive/ESPECIALIZACION IA/BD_ACTIVIDAD4.xlsx"

df = pd.read_excel(excel_path)
print(df)

# Ciclo while para ejecutar el programa y las opciones del menú
while True:
    print("\n Programar Gestión de Clientes: ")
    print("1. Visualizar todos los datos")
    print("2. Añadir cliente")
    print("3. Eliminar cliente")
    print("4. Modificar cliente")
    print("5. Listar/Ordenar clientes por Nombre")
    print("6. Listar/Ordenar clientes por Edad")
    print("7. Listar/Ordenar clientes por Valor de la compra $")
    print("8. Consultar cliente por ID")
    print("9. Salir")

    # Pedimos la opción del menú y la casteamos en int y así también con las opciones de añadir cliente
    opcion = int(input("Por favor selecciona una opción: "))

    if opcion == 1:
        # Visualizar todos los datos
        print("\nDatos de todos los clientes:")
        print(df)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 2:
        # Añadir cliente
        # Aqui usamos un condicional para que el ID aumente automáticamente al final del dataframe
        # siempre y cuando el dataframe no se encuentre vacío, para ello se aumenta en 1 el útlimo ID de la base de datos
        if df.empty:
            id = 1
        else:
            id = df['ID'].max() + 1

        nombre = input("Por favor, ingrese el nombre del cliente: ")
        correo = input("Por favor, ingrese el correo del cliente: ")
        telefono = input("Por favor, ingrese el teléfono del cliente: ")
        edad = int(input("Por favor, ingrese la edad del cliente: "))
        v_compra = float(input("Por favor, ingrese el valor de la compra del cliente: $"))
        ciudad = input("Por favor, ingrese la ciudad del cliente: ")

        # Añadir el cliente al DataFrame
        # Creamos un dataframe temporal que nos ayuda a guardar los datos del nuevo cliente.
        # con la función concat unimnos el dataframe temporal con el de la base de datos que estamos usando
        # usamos ignore_index=True para asegurarnos de que los índices se vuelven a enumerar correctamente para mantener el orden
        df = pd.concat([df, pd.DataFrame({'ID': [id], 'Nombre': [nombre], 'Correo': [correo],
                                   'Teléfono': [telefono], 'Edad': [edad], 'Valor de la Compra': [v_compra], 'Ciudad': [ciudad]})],
                                   ignore_index=True)
        print("El cliente se ha agregado al sistema con ID:", id)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 3:
        # Eliminar cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a eliminar: "))

        # Eliminar el cliente del dataframe
        # En esta parte del código se reescribe el dataframe excluyendo las filas del cliente que se desea eliminar
        # basados en el ID
        df = df[df['ID'] != id]
        print("El cliente ha sido eliminado del sistema")
        input("Por favor presiona ENTER para continuar")

    elif opcion == 4:
        # Modificar datos del cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a modificar: "))

        # Aqui medisnte un condicional se busca el cliente en el dataframe y se compara
        # con ayuda del ID, en el caso de ser True permite modificar el cliente y en el caso de ser False
        # se informa que no se encontró el cliente
        if id in df['ID'].values:
            nombre = input("Por favor, ingrese el nuevo nombre del cliente: ")
            correo = input("Por favor, ingrese el nuevo correo del cliente: ")
            telefono = input("Por favor, ingrese el nuevo teléfono del cliente: ")
            edad = input("Por favor, ingrese la nueva edad del cliente: ")
            v_compra = input("Por favor, ingrese el nuevo valor de la compra del cliente: $")
            ciudad = input("Por favor, ingrese la nueva ciudad del cliente: ")

            # Se verifica si se ha modificado la información en cada campo con un condicional
            # de True o Flase y en caso de ser True se reemplaza el dato en el campo respectivo
            # con ayuda de la función .loc y se añade al datafrane.

            if nombre:
                df.loc[df['ID'] == id, 'Nombre'] = nombre
            if correo:
                df.loc[df['ID'] == id, 'Correo'] = correo
            if telefono:
                df.loc[df['ID'] == id, 'Teléfono'] = telefono
            if edad:
                df.loc[df['ID'] == id, 'Edad'] = int(edad)
            if v_compra:
                df.loc[df['ID'] == id, 'Valor de la Compra'] = float(v_compra)
            if ciudad:
                df.loc[df['ID'] == id, 'Ciudad'] = ciudad

            print("El cliente se ha modificado en el sistema.")
            input("Por favor presiona ENTER para continuar")
        else:
            print("Cliente no encontrado en nuestro sistema.")
            input("Por favor presiona ENTER para continuar")

    elif opcion == 5:
        # Listar/Ordenar clientes por nombre
        # Aqui se ordenan los clientes usando la función sort
        clientes_ordenados = df.sort_values(by='Nombre')

        # Imprimir los clientes ordenados por nombre
        print(clientes_ordenados)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 6:
        # Listar/Ordenar clientes por edad
        # Aqui se ordenan los clientes usando la función sort
        clientes_ordenados = df.sort_values(by='Edad')

        # Imprimir los clientes ordenados por edad
        print(clientes_ordenados)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 7:
        # Listar/Ordenar clientes por valor de la compra
        # Aqui se ordenan los clientes usando la función sort
        clientes_ordenados = df.sort_values(by='Valor de la Compra')

        # Imprimir los clientes ordenados por valor de la compra
        print(clientes_ordenados)
        input("Por favor presiona ENTER para continuar")

    elif opcion == 8:
        # Consultar cliente por ID
        id = int(input("Por favor, ingrese el ID del cliente a consultar: "))

        # Buscar el cliente en el dataframe
        # Para esta función comparamos el ID ingresado con los ID's de la base de datos
        # y comprobamos si existe o no, y se muestra el dataframe que cumpla con la condición
        cliente = df[df['ID'] == id]

        if not cliente.empty: # aquí se verifica si el dataframe no está vacío y se muestra la información
            print(cliente)
        else:
            print("Cliente no encontrado.")
        input("Por favor presiona ENTER para continuar")

    elif opcion == 9:
        print("--> Saliendo del programa--->")
        break

    else:
        print("Opción no válida, por favor intente de nuevo.")
        input("Por favor presiona ENTER para continuar")